### ISSUE TITLE
The weapon is damaged and cannot be repaired.

### ISSUE THREAD

**Issue by jsRuner** [Xian55/WowClassicGrindBot#616] opened 2024-07-31 04:37 UTC
### Description

The current judgment condition for repair is "item broken". I'm playing as a hunter. The first item to break is the bow. It's too late to repair it when it's broken because there are many monsters on the way to the repair place, resulting in continuous deaths.

Warriors also encountered the same situation

It should be possible to add conditions, such as the proportion of equipment damage. For example, when the durability is 30%, it should be repaired.  

### Addon Version

latest

### World of Warcraft Client

The Burning Crusade Classic

### Reproduction Steps

It should be possible to add conditions, such as the proportion of equipment damage. For example, when the durability is 30%, it should be repaired.  

### Screenshots

It should be possible to add conditions, such as the proportion of equipment damage. For example, when the durability is 30%, it should be repaired.  

### Logs

It should be possible to add conditions, such as the proportion of equipment damage. For example, when the durability is 30%, it should be repaired.

**Comment by Xian55** [comment] 2024-07-31 08:31
Hello, if im reading it correctly this is a duplicate of https://github.com/Xian55/WowClassicGrindBot/issues/444

Especially after reading https://github.com/Xian55/WowClassicGrindBot/issues/444#issuecomment-1289993742

With https://github.com/Xian55/WowClassicGrindBot/pull/387, such functionality has been already added.

The existing profiles are outdated, however there should be plenty of example of what kind of conditions you can use, 
for `Durability%`
https://github.com/search?q=repo%3AXian55%2FWowClassicGrindBot%20Durability%25&type=code

Have a good day!

**Closed as completed by Xian55** 2024-07-31 08:31 UTC
Labels: bug
